import jsPDF from 'jspdf'

/**
 * Generates a PDF document from template content
 * @param {string} title - Document title
 * @param {string} content - Document content (HTML or plain text)
 * @param {Object} userInfo - User information for personalization
 * @returns {void} - Downloads the PDF
 */
export function generatePDF(title, content, userInfo = {}) {
  try {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 20
    const maxWidth = pageWidth - (margin * 2)
    
    let yPosition = margin
    
    // Add header
    doc.setFontSize(20)
    doc.setFont(undefined, 'bold')
    const titleLines = doc.splitTextToSize(title, maxWidth)
    doc.text(titleLines, margin, yPosition)
    yPosition += titleLines.length * 10 + 10
    
    // Add date
    doc.setFontSize(10)
    doc.setFont(undefined, 'normal')
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, margin, yPosition)
    yPosition += 15
    
    // Add user info if provided
    if (userInfo.name || userInfo.email) {
      doc.setFontSize(12)
      doc.setFont(undefined, 'bold')
      doc.text('Document Information:', margin, yPosition)
      yPosition += 8
      
      doc.setFont(undefined, 'normal')
      if (userInfo.name) {
        doc.text(`Name: ${userInfo.name}`, margin, yPosition)
        yPosition += 6
      }
      if (userInfo.email) {
        doc.text(`Email: ${userInfo.email}`, margin, yPosition)
        yPosition += 6
      }
      yPosition += 10
    }
    
    // Add content
    doc.setFontSize(11)
    doc.setFont(undefined, 'normal')
    
    // Clean HTML content (basic cleanup)
    const cleanContent = content
      .replace(/<[^>]*>/g, '') // Remove HTML tags
      .replace(/&nbsp;/g, ' ')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .trim()
    
    const contentLines = doc.splitTextToSize(cleanContent, maxWidth)
    
    // Add content with page breaks
    for (let i = 0; i < contentLines.length; i++) {
      if (yPosition > pageHeight - margin) {
        doc.addPage()
        yPosition = margin
      }
      doc.text(contentLines[i], margin, yPosition)
      yPosition += 6
    }
    
    // Add footer disclaimer
    yPosition += 20
    if (yPosition > pageHeight - 40) {
      doc.addPage()
      yPosition = margin
    }
    
    doc.setFontSize(8)
    doc.setFont(undefined, 'italic')
    const disclaimer = 'DISCLAIMER: This document is generated by LegalEase and is not legal advice. Please consult with a qualified attorney for legal matters.'
    const disclaimerLines = doc.splitTextToSize(disclaimer, maxWidth)
    doc.text(disclaimerLines, margin, yPosition)
    
    // Add page numbers
    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 40, pageHeight - 10)
    }
    
    // Download the PDF
    const fileName = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.pdf`
    doc.save(fileName)
    
    return { success: true, fileName }
  } catch (error) {
    console.error('Error generating PDF:', error)
    return { success: false, error: error.message }
  }
}

/**
 * Generates a legal document template PDF with form fields
 * @param {Object} template - Template object with title and content
 * @param {Object} formData - User-filled form data
 * @returns {void} - Downloads the PDF
 */
export function generateTemplatePDF(template, formData = {}) {
  try {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 20
    const maxWidth = pageWidth - (margin * 2)
    
    let yPosition = margin
    
    // Add header
    doc.setFontSize(18)
    doc.setFont(undefined, 'bold')
    const titleLines = doc.splitTextToSize(template.title, maxWidth)
    doc.text(titleLines, margin, yPosition)
    yPosition += titleLines.length * 8 + 15
    
    // Add date and user info
    doc.setFontSize(10)
    doc.setFont(undefined, 'normal')
    doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, yPosition)
    yPosition += 10
    
    // Process template content and replace placeholders
    let processedContent = template.templateContent || template.content || ''
    
    // Replace common placeholders with form data
    Object.entries(formData).forEach(([key, value]) => {
      const placeholder = new RegExp(`\\[${key.toUpperCase()}\\]`, 'g')
      processedContent = processedContent.replace(placeholder, value || `[${key.toUpperCase()}]`)
    })
    
    // Clean and format content
    const cleanContent = processedContent
      .replace(/<[^>]*>/g, '\n') // Replace HTML tags with line breaks
      .replace(/&nbsp;/g, ' ')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/\n\s*\n/g, '\n\n') // Clean up multiple line breaks
      .trim()
    
    // Add content
    doc.setFontSize(11)
    doc.setFont(undefined, 'normal')
    
    const contentLines = doc.splitTextToSize(cleanContent, maxWidth)
    
    for (let i = 0; i < contentLines.length; i++) {
      if (yPosition > pageHeight - 40) {
        doc.addPage()
        yPosition = margin
      }
      doc.text(contentLines[i], margin, yPosition)
      yPosition += 6
    }
    
    // Add signature section
    yPosition += 20
    if (yPosition > pageHeight - 80) {
      doc.addPage()
      yPosition = margin
    }
    
    doc.setFont(undefined, 'normal')
    doc.text('Signature: _________________________    Date: _____________', margin, yPosition)
    yPosition += 15
    doc.text('Print Name: _________________________', margin, yPosition)
    
    // Add footer disclaimer
    yPosition += 30
    if (yPosition > pageHeight - 40) {
      doc.addPage()
      yPosition = margin
    }
    
    doc.setFontSize(8)
    doc.setFont(undefined, 'italic')
    const disclaimer = 'DISCLAIMER: This document template is provided by LegalEase for informational purposes only and does not constitute legal advice. Please consult with a qualified attorney before using this document for legal purposes.'
    const disclaimerLines = doc.splitTextToSize(disclaimer, maxWidth)
    doc.text(disclaimerLines, margin, yPosition)
    
    // Add page numbers
    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 40, pageHeight - 10)
    }
    
    // Download the PDF
    const fileName = `${template.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.pdf`
    doc.save(fileName)
    
    return { success: true, fileName }
  } catch (error) {
    console.error('Error generating template PDF:', error)
    return { success: false, error: error.message }
  }
}
